# Site Info
title:              "mhr380"
description:        "mhr380's notes"
author_name:        "mhr380"
# logo_url:           https://avatars.githubusercontent.com/u/7625670?v=4
logo_url:           /assets/avatar.png
favicon_url:        /assets/favicon.jfif

# Site Settings
url:                https://mhr380.github.io
baseurl:            ""
permalink:          /posts/:title
timezone:           Asia/Tokyo
mathjax:            true  # enables support for mathjax - set to 'false' to disable
social_share_previews: true

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script", "serve.bat" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
